[project]
name = 'Blockchain-Based-Inventory-Management-Cross-Docking-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.quality-control]
path = 'contracts/quality-control.clar'
clarity_version = 2
epoch = 2.5

[contracts.scheduling-management]
path = 'contracts/scheduling-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
